#############################################################################
# Makefile for building: Project
# Generated by qmake (3.1) (Qt 5.9.0)
# Project:  Project.pro
# Template: app
# Command: /home/emma/Qt5.9.0/5.9/gcc_64/bin/qmake -o Makefile Project.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT5BUILD -DGL42 -DLINUX -DQT_QML_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -msse -msse2 -msse3 -I/usr/include/SDL2 -D_REENTRANT -march=native -g -std=gnu++11 -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/emma/NGL/include -Iusr/include/ -Iinclude -I/home/emma/Qt5.9.0/5.9/gcc_64/include -I/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui -I/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/linux-g++
QMAKE         = /home/emma/Qt5.9.0/5.9/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL_FILE = /home/emma/Qt5.9.0/5.9/gcc_64/bin/qmake -install qinstall file
QINSTALL_PROGRAM = /home/emma/Qt5.9.0/5.9/gcc_64/bin/qmake -install qinstall program
QINSTALL_DIR  = /home/emma/Qt5.9.0/5.9/gcc_64/bin/qmake -install qinstall directory
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Project1.0.0
DISTDIR = /home/emma/Documents/Computing\ for\ Animation/Project/obj/Project1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/emma/Qt5.9.0/5.9/gcc_64/lib
LIBS          = $(SUBLIBS) -L/$(HOME)/NGL/lib -l NGL -L/usr/lib/x86_64-linux-gnu -lSDL2 -lSDL2_ttf -lSDL2_image -L/usr/local/lib -L/home/emma/Qt5.9.0/5.9/gcc_64/lib -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/Car.cpp \
		src/Game.cpp \
		src/GameEnv.cpp \
		src/GameLoop.cpp \
		src/main.cpp \
		src/Menu.cpp \
		src/Projectile.cpp \
		src/Ship.cpp 
OBJECTS       = obj/Car.o \
		obj/Game.o \
		obj/GameEnv.o \
		obj/GameLoop.o \
		obj/main.o \
		obj/Menu.o \
		obj/Projectile.o \
		obj/Ship.o
DIST          = .qmake.stash \
		Project.pro include/Car.h \
		include/Game.h \
		include/GameEnv.h \
		include/GameLoop.h \
		include/Menu.h \
		include/Projectile.h \
		include/Ship.h src/Car.cpp \
		src/Game.cpp \
		src/GameEnv.cpp \
		src/GameLoop.cpp \
		src/main.cpp \
		src/Menu.cpp \
		src/Projectile.cpp \
		src/Ship.cpp
QMAKE_TARGET  = Project
DESTDIR       = 
TARGET        = Project


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Project.pro .qmake.cache /home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/linux-g++/qmake.conf /home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/spec_pre.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/common/unix.conf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/common/linux.conf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/common/sanitize.conf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/common/gcc-base.conf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/common/g++-base.conf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/common/g++-unix.conf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/qconfig.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt_functions.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt_config.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		.qmake.stash \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/toolchain.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/default_pre.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/resolve_config.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/default_post.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/qml_debug.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/warn_on.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/resources.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/moc.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/unix/thread.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/qmake_use.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/file_copies.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/exceptions.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/yacc.prf \
		/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/lex.prf \
		Project.pro \
		/home/emma/Qt5.9.0/5.9/gcc_64/lib/libQt5Gui.prl \
		/home/emma/Qt5.9.0/5.9/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Project.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/spec_pre.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/common/unix.conf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/common/linux.conf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/common/sanitize.conf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/common/gcc-base.conf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/common/g++-base.conf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/common/g++-unix.conf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/qconfig.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt_functions.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt_config.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/spec_post.prf:
.qmake.cache:
.qmake.stash:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/toolchain.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/default_pre.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/resolve_config.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/default_post.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/qml_debug.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/warn_on.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/resources.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/moc.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/unix/opengl.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/unix/thread.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/qmake_use.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/file_copies.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/testcase_targets.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/exceptions.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/yacc.prf:
/home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/lex.prf:
Project.pro:
/home/emma/Qt5.9.0/5.9/gcc_64/lib/libQt5Gui.prl:
/home/emma/Qt5.9.0/5.9/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Project.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/Car.h include/Game.h include/GameEnv.h include/GameLoop.h include/Menu.h include/Projectile.h include/Ship.h $(DISTDIR)/
	$(COPY_FILE) --parents src/Car.cpp src/Game.cpp src/GameEnv.cpp src/GameLoop.cpp src/main.cpp src/Menu.cpp src/Projectile.cpp src/Ship.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -msse -msse2 -msse3 -I/usr/include/SDL2 -D_REENTRANT -march=native -g -std=gnu++11 -Wall -W -Wno-unused-parameter -dM -E -o moc_predefs.h /home/emma/Qt5.9.0/5.9/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

obj/Car.o: src/Car.cpp include/Car.h \
		/home/emma/NGL/include/ngl/Mat4.h \
		/home/emma/NGL/include/ngl/Types.h \
		/home/emma/NGL/include/ngl/glew.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/QGLContext \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qgl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopengl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtguiglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtcore-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsystemdetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocessordetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtypeinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsysinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlogging.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qflags.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbasicatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qgenericatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobalstatic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmutex.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qnumeric.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qversiontagging.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtgui-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qt_windows.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopengles2ext.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopenglext.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qwidget.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qwindowdefs.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qnamespace.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstring.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qchar.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearray.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qrefcount.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qarraydata.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringbuilder.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qalgorithms.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qiterator.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qhashfunctions.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qpair.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearraylist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringlist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qregexp.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringmatcher.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcoreevent.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qscopedpointer.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmetatype.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmargins.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpaintdevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qrect.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsize.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qpoint.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpalette.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qcolor.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qrgb.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qrgba64.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qbrush.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvector.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qmatrix.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpolygon.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qregion.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qdatastream.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qiodevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qline.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtransform.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpainterpath.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qimage.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpixelformat.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpixmap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsharedpointer.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qshareddata.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qhash.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfont.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfontmetrics.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfontinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qcursor.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qkeysequence.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qevent.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvariant.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qdebug.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtextstream.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlocale.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qset.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qurl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qurlquery.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qfile.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qfiledevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qvector2d.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtouchdevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpaintengine.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpainter.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtextoption.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpen.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/QSurfaceFormat \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/emma/NGL/include/ngl/Vec3.h \
		/home/emma/NGL/include/ngl/Obj.h \
		/home/emma/NGL/include/ngl/Texture.h \
		/home/emma/NGL/include/ngl/Image.h \
		/home/emma/NGL/include/ngl/Colour.h \
		/home/emma/NGL/include/ngl/Vec4.h \
		/home/emma/NGL/include/ngl/Vec2.h \
		/home/emma/NGL/include/ngl/AbstractMesh.h \
		/home/emma/NGL/include/ngl/BBox.h \
		/home/emma/NGL/include/ngl/AbstractVAO.h \
		/home/emma/NGL/include/ngl/RibExport.h \
		/home/emma/NGL/include/ngl/NGLassert.h \
		/home/emma/NGL/include/ngl/ShaderLib.h \
		/home/emma/NGL/include/ngl/Shader.h \
		/home/emma/NGL/include/ngl/ShaderProgram.h \
		/home/emma/NGL/include/ngl/Util.h \
		/home/emma/NGL/include/ngl/Singleton.h \
		/home/emma/NGL/include/ngl/Mat3.h \
		/home/emma/NGL/include/ngl/VAOPrimitives.h \
		/home/emma/NGL/include/ngl/NGLStream.h \
		/home/emma/NGL/include/ngl/Transformation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Car.o src/Car.cpp

obj/Game.o: src/Game.cpp include/Game.h \
		/home/emma/NGL/include/ngl/Camera.h \
		/home/emma/NGL/include/ngl/Types.h \
		/home/emma/NGL/include/ngl/glew.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/QGLContext \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qgl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopengl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtguiglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtcore-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsystemdetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocessordetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtypeinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsysinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlogging.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qflags.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbasicatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qgenericatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobalstatic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmutex.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qnumeric.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qversiontagging.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtgui-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qt_windows.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopengles2ext.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopenglext.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qwidget.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qwindowdefs.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qnamespace.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstring.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qchar.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearray.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qrefcount.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qarraydata.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringbuilder.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qalgorithms.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qiterator.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qhashfunctions.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qpair.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearraylist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringlist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qregexp.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringmatcher.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcoreevent.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qscopedpointer.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmetatype.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmargins.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpaintdevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qrect.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsize.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qpoint.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpalette.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qcolor.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qrgb.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qrgba64.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qbrush.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvector.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qmatrix.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpolygon.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qregion.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qdatastream.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qiodevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qline.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtransform.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpainterpath.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qimage.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpixelformat.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpixmap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsharedpointer.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qshareddata.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qhash.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfont.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfontmetrics.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfontinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qcursor.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qkeysequence.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qevent.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvariant.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qdebug.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtextstream.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlocale.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qset.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qurl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qurlquery.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qfile.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qfiledevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qvector2d.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtouchdevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpaintengine.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpainter.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtextoption.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpen.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/QSurfaceFormat \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/emma/NGL/include/ngl/Vec4.h \
		/home/emma/NGL/include/ngl/Vec2.h \
		/home/emma/NGL/include/ngl/Vec3.h \
		/home/emma/NGL/include/ngl/Mat4.h \
		/home/emma/NGL/include/ngl/RibExport.h \
		/home/emma/NGL/include/ngl/Plane.h \
		/home/emma/NGL/include/ngl/AABB.h \
		/home/emma/NGL/include/ngl/BBox.h \
		/home/emma/NGL/include/ngl/AbstractVAO.h \
		/home/emma/NGL/include/ngl/Light.h \
		/home/emma/NGL/include/ngl/Colour.h \
		/home/emma/NGL/include/ngl/ShaderLib.h \
		/home/emma/NGL/include/ngl/Shader.h \
		/home/emma/NGL/include/ngl/ShaderProgram.h \
		/home/emma/NGL/include/ngl/Util.h \
		/home/emma/NGL/include/ngl/Singleton.h \
		/home/emma/NGL/include/ngl/Mat3.h \
		include/Car.h \
		/home/emma/NGL/include/ngl/Obj.h \
		/home/emma/NGL/include/ngl/Texture.h \
		/home/emma/NGL/include/ngl/Image.h \
		/home/emma/NGL/include/ngl/AbstractMesh.h \
		/home/emma/NGL/include/ngl/NGLassert.h \
		/home/emma/NGL/include/ngl/NGLInit.h \
		/home/emma/NGL/include/ngl/VAOPrimitives.h \
		/home/emma/NGL/include/ngl/Material.h \
		/home/emma/NGL/include/ngl/NGLStream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Game.o src/Game.cpp

obj/GameEnv.o: src/GameEnv.cpp include/GameEnv.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GameEnv.o src/GameEnv.cpp

obj/GameLoop.o: src/GameLoop.cpp include/GameLoop.h \
		/home/emma/NGL/include/ngl/NGLInit.h \
		/home/emma/NGL/include/ngl/Singleton.h \
		/home/emma/NGL/include/ngl/Types.h \
		/home/emma/NGL/include/ngl/glew.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/QGLContext \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qgl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopengl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtguiglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtcore-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsystemdetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocessordetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtypeinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsysinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlogging.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qflags.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbasicatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qgenericatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobalstatic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmutex.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qnumeric.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qversiontagging.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtgui-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qt_windows.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopengles2ext.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopenglext.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qwidget.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qwindowdefs.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qnamespace.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstring.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qchar.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearray.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qrefcount.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qarraydata.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringbuilder.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qalgorithms.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qiterator.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qhashfunctions.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qpair.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearraylist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringlist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qregexp.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringmatcher.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcoreevent.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qscopedpointer.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmetatype.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmargins.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpaintdevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qrect.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsize.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qpoint.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpalette.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qcolor.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qrgb.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qrgba64.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qbrush.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvector.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qmatrix.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpolygon.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qregion.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qdatastream.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qiodevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qline.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtransform.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpainterpath.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qimage.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpixelformat.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpixmap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsharedpointer.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qshareddata.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qhash.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfont.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfontmetrics.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfontinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qcursor.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qkeysequence.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qevent.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvariant.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qdebug.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtextstream.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlocale.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qset.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qurl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qurlquery.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qfile.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qfiledevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qvector2d.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtouchdevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpaintengine.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpainter.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtextoption.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpen.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/QSurfaceFormat \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/emma/NGL/include/ngl/VAOPrimitives.h \
		/home/emma/NGL/include/ngl/Vec3.h \
		/home/emma/NGL/include/ngl/AbstractVAO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GameLoop.o src/GameLoop.cpp

obj/main.o: src/main.cpp include/Menu.h \
		include/GameLoop.h \
		/home/emma/NGL/include/ngl/NGLInit.h \
		/home/emma/NGL/include/ngl/Singleton.h \
		/home/emma/NGL/include/ngl/Types.h \
		/home/emma/NGL/include/ngl/glew.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/QGLContext \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qgl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopengl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtguiglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtcore-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsystemdetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocessordetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtypeinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsysinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlogging.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qflags.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbasicatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qgenericatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobalstatic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmutex.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qnumeric.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qversiontagging.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtgui-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qt_windows.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopengles2ext.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopenglext.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qwidget.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qwindowdefs.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qnamespace.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstring.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qchar.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearray.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qrefcount.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qarraydata.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringbuilder.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qalgorithms.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qiterator.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qhashfunctions.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qpair.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearraylist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringlist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qregexp.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringmatcher.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcoreevent.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qscopedpointer.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmetatype.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmargins.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpaintdevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qrect.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsize.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qpoint.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpalette.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qcolor.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qrgb.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qrgba64.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qbrush.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvector.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qmatrix.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpolygon.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qregion.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qdatastream.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qiodevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qline.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtransform.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpainterpath.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qimage.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpixelformat.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpixmap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsharedpointer.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qshareddata.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qhash.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfont.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfontmetrics.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfontinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qcursor.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qkeysequence.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qevent.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvariant.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qdebug.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtextstream.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlocale.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qset.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qurl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qurlquery.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qfile.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qfiledevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qvector2d.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtouchdevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpaintengine.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpainter.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtextoption.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpen.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/QSurfaceFormat \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/emma/NGL/include/ngl/VAOPrimitives.h \
		/home/emma/NGL/include/ngl/Vec3.h \
		/home/emma/NGL/include/ngl/AbstractVAO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/Menu.o: src/Menu.cpp include/Menu.h \
		include/GameLoop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Menu.o src/Menu.cpp

obj/Projectile.o: src/Projectile.cpp include/Projectile.h \
		/home/emma/NGL/include/ngl/Vec3.h \
		/home/emma/NGL/include/ngl/Types.h \
		/home/emma/NGL/include/ngl/glew.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/QGLContext \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qgl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopengl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtguiglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtcore-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsystemdetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocessordetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtypeinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsysinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlogging.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qflags.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbasicatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qgenericatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobalstatic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmutex.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qnumeric.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qversiontagging.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtgui-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qt_windows.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopengles2ext.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopenglext.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qwidget.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qwindowdefs.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qnamespace.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstring.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qchar.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearray.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qrefcount.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qarraydata.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringbuilder.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qalgorithms.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qiterator.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qhashfunctions.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qpair.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearraylist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringlist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qregexp.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringmatcher.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcoreevent.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qscopedpointer.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmetatype.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmargins.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpaintdevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qrect.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsize.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qpoint.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpalette.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qcolor.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qrgb.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qrgba64.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qbrush.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvector.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qmatrix.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpolygon.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qregion.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qdatastream.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qiodevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qline.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtransform.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpainterpath.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qimage.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpixelformat.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpixmap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsharedpointer.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qshareddata.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qhash.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfont.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfontmetrics.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfontinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qcursor.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qkeysequence.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qevent.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvariant.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qdebug.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtextstream.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlocale.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qset.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qurl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qurlquery.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qfile.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qfiledevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qvector2d.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtouchdevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpaintengine.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpainter.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtextoption.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpen.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/QSurfaceFormat \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/emma/NGL/include/ngl/Obj.h \
		/home/emma/NGL/include/ngl/Texture.h \
		/home/emma/NGL/include/ngl/Image.h \
		/home/emma/NGL/include/ngl/Colour.h \
		/home/emma/NGL/include/ngl/Vec4.h \
		/home/emma/NGL/include/ngl/Vec2.h \
		/home/emma/NGL/include/ngl/AbstractMesh.h \
		/home/emma/NGL/include/ngl/BBox.h \
		/home/emma/NGL/include/ngl/AbstractVAO.h \
		/home/emma/NGL/include/ngl/RibExport.h \
		/home/emma/NGL/include/ngl/NGLassert.h \
		/home/emma/NGL/include/ngl/Camera.h \
		/home/emma/NGL/include/ngl/Mat4.h \
		/home/emma/NGL/include/ngl/Plane.h \
		/home/emma/NGL/include/ngl/AABB.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Projectile.o src/Projectile.cpp

obj/Ship.o: src/Ship.cpp include/Ship.h \
		/home/emma/NGL/include/ngl/Vec3.h \
		/home/emma/NGL/include/ngl/Types.h \
		/home/emma/NGL/include/ngl/glew.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/QGLContext \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qgl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopengl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtguiglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtcore-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsystemdetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocessordetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtypeinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsysinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlogging.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qflags.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbasicatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qgenericatomic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobalstatic.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmutex.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qnumeric.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qversiontagging.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtgui-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qt_windows.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopengles2ext.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qopenglext.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qwidget.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qwindowdefs.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qnamespace.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstring.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qchar.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearray.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qrefcount.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qarraydata.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringbuilder.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qalgorithms.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qiterator.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qhashfunctions.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qpair.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearraylist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringlist.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qregexp.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringmatcher.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcoreevent.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qscopedpointer.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmetatype.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmargins.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpaintdevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qrect.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsize.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qpoint.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpalette.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qcolor.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qrgb.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qrgba64.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qbrush.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvector.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qmatrix.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpolygon.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qregion.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qdatastream.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qiodevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qline.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtransform.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpainterpath.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qimage.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpixelformat.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpixmap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsharedpointer.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qshareddata.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qhash.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfont.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfontmetrics.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qfontinfo.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qcursor.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qkeysequence.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qevent.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qvariant.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qmap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qdebug.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qtextstream.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qlocale.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qset.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qurl.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qurlquery.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qfile.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtCore/qfiledevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qvector2d.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtouchdevice.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpaintengine.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpainter.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qtextoption.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qpen.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/QSurfaceFormat \
		/home/emma/Qt5.9.0/5.9/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/emma/NGL/include/ngl/Obj.h \
		/home/emma/NGL/include/ngl/Texture.h \
		/home/emma/NGL/include/ngl/Image.h \
		/home/emma/NGL/include/ngl/Colour.h \
		/home/emma/NGL/include/ngl/Vec4.h \
		/home/emma/NGL/include/ngl/Vec2.h \
		/home/emma/NGL/include/ngl/AbstractMesh.h \
		/home/emma/NGL/include/ngl/BBox.h \
		/home/emma/NGL/include/ngl/AbstractVAO.h \
		/home/emma/NGL/include/ngl/RibExport.h \
		/home/emma/NGL/include/ngl/NGLassert.h \
		/home/emma/NGL/include/ngl/Camera.h \
		/home/emma/NGL/include/ngl/Mat4.h \
		/home/emma/NGL/include/ngl/Plane.h \
		/home/emma/NGL/include/ngl/AABB.h \
		/home/emma/NGL/include/ngl/ShaderLib.h \
		/home/emma/NGL/include/ngl/Shader.h \
		/home/emma/NGL/include/ngl/ShaderProgram.h \
		/home/emma/NGL/include/ngl/Util.h \
		/home/emma/NGL/include/ngl/Singleton.h \
		/home/emma/NGL/include/ngl/Mat3.h \
		/home/emma/NGL/include/ngl/Transformation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Ship.o src/Ship.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

